#!/usr/bin/env node
/* Regenerates src/data/zone-coords.js from the system tzdata zone.tab
   (official IANA coordinates for every timezone). Run when tzdata updates:
   node scripts/gen-coords.js */
"use strict";

const fs = require("fs");
const path = require("path");

const SRC = "/usr/share/zoneinfo/zone.tab";

/* ISO-6709 "+4230+00131" / "+404251-0740023" -> [lat, lon] in degrees. */
function parseISO6709(s) {
  const m = s.match(/^([+-])(\d{2})(\d{2})(\d{2})?([+-])(\d{3})(\d{2})(\d{2})?$/);
  if (!m) return null;
  const lat = (+m[2] + m[3] / 60 + (m[4] ? m[4] / 3600 : 0)) * (m[1] === "-" ? -1 : 1);
  const lon = (+m[6] + m[7] / 60 + (m[8] ? m[8] / 3600 : 0)) * (m[5] === "-" ? -1 : 1);
  return [Math.round(lat * 100) / 100, Math.round(lon * 100) / 100];
}

const lines = fs.readFileSync(SRC, "utf8").split("\n");
const coords = {};
for (const line of lines) {
  if (!line || line.startsWith("#")) continue;
  const [, iso, tz] = line.split("\t");
  if (!iso || !tz) continue;
  const c = parseISO6709(iso.trim());
  if (c) coords[tz.trim()] = c;
}

const entries = Object.keys(coords).sort()
  .map(tz => `  "${tz}": [${coords[tz][0]}, ${coords[tz][1]}]`)
  .join(",\n");

const out = `"use strict";

/* Glass Time — data/zone-coords
   GENERATED by scripts/gen-coords.js from tzdata zone.tab — do not edit by hand.
   Official IANA coordinates for every timezone, so the sun engine is exact for
   all ~${Object.keys(coords).length} zones (not just the curated cities). */
const ZONE_COORDS = {
${entries}
};
`;

const dest = path.join(__dirname, "..", "src", "data", "zone-coords.js");
fs.writeFileSync(dest, out);
console.log(`Wrote ${path.relative(process.cwd(), dest)} (${Object.keys(coords).length} zones, ${out.length} bytes)`);
